# GitGuard Demo Grafana Datasource Configuration
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: true
      alertmanagerUid: "alertmanager"
    secureJsonData: {}
    version: 1

  - name: GitGuard Metrics
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "10s"
      queryTimeout: "30s"
      httpMethod: "GET"
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: "jaeger"
    version: 1
