# Optional local Temporal setup for worker tests
# Usage: docker compose -f docker-compose.temporal.yml up -d

services:
  temporal:
    image: temporalio/auto-setup:1.24.4
    ports:
      - "7233:7233"   # server gRPC
      - "8233:8233"   # web UI
    environment:
      - TEMPORAL_UI_PORT=8233
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres
    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 5 bash -c '</dev/tcp/127.0.0.1/7233'"]
      interval: 5s
      timeout: 3s
      retries: 30
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13.15
    environment:
      POSTGRES_DB: temporal
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - temporal_postgres_data:/var/lib/postgresql/data

volumes:
  temporal_postgres_data:

# To use:
# 1. docker compose -f docker-compose.temporal.yml up -d
# 2. Point your temporalio client at localhost:7233
# 3. Access Temporal Web UI at http://localhost:8233
