# Fly.io configuration for GitGuard
app = "gitguard"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python -m alembic upgrade head"
  strategy = "rolling"

[env]
  PORT = "8080"
  ENVIRONMENT = "production"
  LOG_LEVEL = "info"
  METRICS_ENABLED = "true"
  HEALTH_CHECK_PATH = "/health"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

    [http_service.checks.headers]
      Content-Type = "application/json"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

    [services.http_checks.headers]
      Content-Type = "application/json"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  processes = ["app"]

[processes]
  app = "python apps/guard-api/main.py"
  worker = "python apps/guard-api/worker.py"

[mounts]
  source = "gitguard_data"
  destination = "/data"
  processes = ["app"]

# PostgreSQL configuration
[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"

# Metrics and monitoring
[metrics]
  port = 9090
  path = "/metrics"

# Secrets (set via flyctl secrets)
# flyctl secrets set DATABASE_URL=postgres://...
# flyctl secrets set REDIS_URL=redis://...
# flyctl secrets set GITHUB_APP_PRIVATE_KEY=...
# flyctl secrets set GITHUB_WEBHOOK_SECRET=...

# Volume for persistent data
[[mounts]]
  source = "gitguard_storage"
  destination = "/app/storage"
  processes = ["app"]

# Auto-scaling configuration
[scaling]
  min_machines_running = 1
  max_machines_running = 10

  [[scaling.metrics]]
    type = "cpu"
    target = 70

  [[scaling.metrics]]
    type = "memory"
    target = 80

# Backup configuration
[backup]
  schedule = "0 2 * * *"  # Daily at 2 AM
  retention = "7d"

# Environment-specific overrides
[env.production]
  LOG_LEVEL = "info"
  DEBUG = "false"
  METRICS_ENABLED = "true"

[env.staging]
  LOG_LEVEL = "debug"
  DEBUG = "true"
  METRICS_ENABLED = "true"
