[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
fix = true

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "PL"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_configs = true
pretty = true
# Exclude directories with hyphens in names (not valid Python package names)
exclude = [
    "apps/guard-api/",
    "apps/guard-brain/",
    "apps/guard-ci/",
    "apps/guard-codex/"
]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
