[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E", "F", "I", "B", "UP", "PL"]
ignore = ["E501"]
fix = true

[tool.mypy]
python_version = "3.11"
strict = true
warn_unused_configs = true
pretty = true

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
