name: Bug report
description: Something isn't working as expected
labels: [bug, triage]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve GitGuard! Please fill in the details below.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the bug
      placeholder: Policy evaluation always returns DENY for valid inputs
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps with minimal repro (commands, sample repo/policy, config)
      render: bash
      placeholder: |
        1. `git clone ...`
        2. `docker compose -f docker-compose.demo.yml up`
        3. Call POST /evaluate with payload X
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior and logs
      render: text
  - type: input
    id: version
    attributes:
      label: Version / image tag
      placeholder: e.g., v0.1.0 or ghcr.io/ava-prime/gitguard:0.1.0
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: OS, Python, Docker version, CI provider
  - type: checkboxes
    id: regression
    attributes:
      label: Regression?
      options:
        - label: This worked in a previous version
  - type: textarea
    id: extra
    attributes:
      label: Additional context
