blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/Ava-Prime/gitguard/security/advisories/new
    about: Please use GitHub Security Advisories for confidential security reports.
  - name: Questions & discussion
    url: https://github.com/Ava-Prime/gitguard/discussions
    about: Ask questions, propose ideas, and chat with maintainers here.
