name: Feature request
description: Propose a new capability or improvement
labels: [enhancement, triage]
assignees: []
body:
  - type: input
    id: problem
    attributes:
      label: Problem statement
      placeholder: What user need or pain are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe the UX/API/config, and any alternatives you considered
    validations:
      required: true
  - type: textarea
    id: value
    attributes:
      label: Value / impact
      placeholder: Why this matters; who benefits
  - type: textarea
    id: scope
    attributes:
      label: Scope / non-goals
      placeholder: What this feature will NOT do
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: Checkable outcomes or tests that define "done"
