name: Feature request
description: Propose an enhancement
title: "[FEAT] "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What and why?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Clear pass/fail checks
      placeholder: |
        - [ ] ...
        - [ ] ...
