name: Security Vulnerability Report
description: Report a security vulnerability in GitGuard
title: "[SECURITY] "
labels: ["security", "vulnerability", "needs-triage"]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report

        **Please do not report security vulnerabilities through public GitHub issues.**

        If this is a critical security issue, please email us directly at security@gitguard.dev instead of using this form.

        For non-critical security issues, you may use this template.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Low (Information disclosure, minor impact)
        - Medium (Limited access, moderate impact)
        - High (Significant access, major impact)
        - Critical (Full system compromise)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of GitGuard is affected?
      options:
        - Policy Engine
        - GitHub App Integration
        - Webhook Processing
        - Authentication/Authorization
        - API Endpoints
        - Docker/Container Security
        - Dependencies
        - Documentation/Examples
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Provide a clear description of the vulnerability
      placeholder: |
        Describe the vulnerability in detail:
        - What is the issue?
        - How can it be exploited?
        - What is the potential impact?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the vulnerability
      placeholder: |
        1. Set up GitGuard with...
        2. Configure policies...
        3. Send request to...
        4. Observe that...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide details about your environment
      placeholder: |
        - GitGuard version:
        - Deployment method (Docker, source, etc.):
        - Operating system:
        - GitHub Enterprise/Cloud:
        - Other relevant details:
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Security Impact
      description: Describe the potential security impact
      placeholder: |
        - What data could be accessed?
        - What actions could an attacker perform?
        - Who would be affected?
        - Are there any mitigating factors?
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing this vulnerability, please share them
      placeholder: |
        - Potential fixes or workarounds
        - Configuration changes that could help
        - Code changes (if applicable)

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your commitment to responsible disclosure
      options:
        - label: I will not publicly disclose this vulnerability until it has been addressed
          required: true
        - label: I have not shared details of this vulnerability with others
          required: true
        - label: I understand this may take time to investigate and fix
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: |
        - Related CVEs or security advisories
        - Similar issues in other projects
        - Timeline constraints
        - Contact information for follow-up
