name: Docs & Markdown checks
on:
  pull_request:
    paths:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
      - uses: streetsidesoftware/cspell-action@v7
        with:
          inline: true
          config: .cspell.json
