name: Docs & Markdown checks
on:
  pull_request:
    paths:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
      - uses: streetsidesoftware/cspell-action@v2
        with:
          inline: true
          config: .cspell.json
