name: Docs & Markdown checks
on:
  pull_request:
    paths:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
      - uses: streetsidesoftware/cspell-action@v7
        with:
          inline: true
          config: .cspell.json
